### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by iamchriswick** [benitolopez/generator-wp-s-theme#1]
Hi,

Would you consider automating this setup with `gulp-less`, `gulp-watch` and `gulp-livereload`, so it automatically runs`gulp-clean` and `gulp-build` when changes are saved to a file?

**Comment by benitolopez** [comment]
`gulp-less` can't be used because Underscores uses scss files. And you don't need `gulp-watch` to listen for a change, because this setup already uses the native `watch` task of Gulp: [watch](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpwatchglob--opts-tasks-or-gulpwatchglob--opts-cb). Just run `gulp`. 

PS. There was an error on the .scss files, solved in the v.1.0.3, just update your Gulpfile.js file if you're using a previous version: (https://github.com/benitolopez/generator-wp-s-theme/commit/0b79b509bd5c6b3cc9fbe587acc11e2fd904dd0f)

`gulp-livereload` can be integrated easily. I will publish an update in the next hours. 

Regarding the possibility to include the `gulp-build` task in the default task... Well, I don't think is a good idea. Why regenerate a zip file on every change? I usually run that task when my theme is ready, before the deploy. Not during the development.

**Comment by iamchriswick** [comment]
I found a LESS version of Underscores: https://github.com/mrpritchett/_s-LESS

**Comment by benitolopez** [comment]
This generator uses the official version of Underscores that uses SASS. Also, that version of Underscores with LESS is not updated (last commit was 10 months ago).

By the way, a LESS version is not planned.

**Comment by benitolopez** [comment]
Livereload included (https://github.com/benitolopez/generator-wp-s-theme/commit/ba39470505f82273ab6c4d9234ff60f575f44f6a)
